MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Models/Calisan.cs
namespace MvcOnIkiSubat.Models
{
    public class Calisan
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Age { get; set; }
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Models/ErrorViewModel.cs
namespace MvcOnIkiSubat.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Controllers/GoruntuController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcOnIkiSubat.Controllers
{
    public class GoruntuController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.SiteMsg = 45;
            return View();
        }
        public IActionResult Index2()
        {
            ViewData["SiteMsg2"] = 754;
            return View();
        }
        public IActionResult Index3()
        {
            ViewBag.SiteMsgIndex3 = 9;
            ViewData["SiteMsg3"] = 99;
            return View();
        }
        public IActionResult Index4()
        {
            ViewData["SiteMsg4"] = 800;
            return View();
        }
        public IActionResult Index5()
        {
            ViewData["SiteMsg5"] = 801;
            return View();
        }
        public IActionResult Index6()
        {
            List<int> numbers = new List<int>();
            for (int i = 1; i <= 20; i++)
            {
                numbers.Add(i);
            }
            ViewData["SiteMsg6"] = numbers;
            return View();
        }
        public IActionResult Index7()
        {
            List<int> numbers = new List<int>();
            for (int i = 1; i <= 20; i++)
            {
                numbers.Add(i);
            }
            ViewData["SiteMsg7"] = numbers;
            return View();
        }
        public IActionResult Rastgele()
        {
            var randomNumber = new Random();
            ViewData["SiteRandom1"] = randomNumber.Next(1, 101);
            return View();
        }
        public IActionResult Rastgele2()
        {
            var randomNumber = new Random();
            ViewData["SiteRandom2"] = randomNumber.Next(1, 101);
            return View();
        }
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcOnIkiSubat.Models;
using System.Diagnostics;

namespace MvcOnIkiSubat.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.test1 = 1;
            ViewData["test2"] = 2;
            TempData["test3"] = 3;
            return View();
        }

        public IActionResult Privacy()
        {
            ViewBag.test4 = 4;
            ViewData["test5"] = 5;
            TempData["test6"] = 6;
            return RedirectToAction("Index2");
            //return View();
        }
        public IActionResult Index2()
        {
            return View();
        }
        public IActionResult Index3()
        {
            ViewBag.sayi = 34;
            ViewData["sayi"] = 44;
            TempData["sayi"] = 54;
            return View();
        }
        public IActionResult YurtIci()
        {
            return View();
        }
        public IActionResult YurtDisi()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Controllers/ModelUygulamaController.cs
using Microsoft.AspNetCore.Mvc;
using MvcOnIkiSubat.Models;
using System.Runtime.CompilerServices;

namespace MvcOnIkiSubat.Controllers
{
    public class ModelUygulamaController : Controller
    {
        public IActionResult Index()
        {
            int sayi = 12;
            return View(sayi);
        }
        public IActionResult Index2()
        {
            List<string> dizi = new List<string>();
            dizi.Add("Masa");
            dizi.Add("Sandalye");
            dizi.Add("Dolap");
            dizi.Add("Tablo");

            return View(dizi);
        }
        public IActionResult Index3()
        {
            string mesaj = "test mesaj";

            return View(mesaj);
        }
        public IActionResult Index4()
        {
            List<Calisan> calisanlar = new List<Calisan>();
            calisanlar.AddRange(new List<Calisan>
            {
                new Calisan { Name = "Ali", Surname = "Kara", Age = 22 },
                new Calisan { Name = "Mehmet", Surname = "Kara", Age = 22 },
                new Calisan { Name = "Necmi", Surname = "Kara", Age = 22 }
            });

            return View(calisanlar);
        }
        public IActionResult Index5()
        {
            Calisan calisan = new Calisan();
            calisan.Name = "Ali";
            calisan.Surname = "Kara";
            calisan.Age = 22;

            return View(calisan);
        }
        [HttpGet]
        public IActionResult Index6()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index6(Calisan calisan)
        {
            return View(calisan);
        }
        public IActionResult Index7(int sayi)
        {
            ///ModelUygulama/Index7?sayi=7
            return View();
        }
        public IActionResult Index8(int id)
        {
            return View();
        }
        public IActionResult Index9()
        {
            return View();
        }
        public IActionResult Index9(int id)
        {
            return View(id);
        }
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Controllers/SatrancController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcOnIkiSubat.Controllers
{
    public class SatrancController : Controller
    {
        public IActionResult Index(int id)
        {
            ViewData["Count"] = id;
            return View();
        }
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index.cshtml
@{

}

<write></write>
<br />
<google>Google</google>
<br />
<kontrol number="21"></kontrol>
<br />
<kontrol number="22"></kontrol>
<br />
<big-famous text="Edirne"></big-famous>
<div>
    @Model
</div>

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index10.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index2.cshtml
@{
    <ul>
        @foreach (var ml in @Model)
        {
            <li>@ml</li>
    }
    </ul>
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index3.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div>

    @{
        @model string;
        @Model
    }
</div>

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index4.cshtml
<table class="table table-hover table-bordered">
    <thead>
        <tr class="text-center">
            <th>Name</th>
            <th>Surname</th>
            <th>Age</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var calisan in Model)
        {
            <tr class="text-center">
                <td>@calisan.Name</td>
                <td>@calisan.Surname</td>
                <td>@calisan.Age</td>
            </tr>
        }
    </tbody>

</table>

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index5.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<ul>

    @{
        <li>Name:@Model.Name</li>
        <li>Surname:@Model.Surname</li>
        <li>Age:@Model.Age</li>
    }
</ul>

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index6.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form asp-action="Index6" asp-controller="ModelUygulama" method="post">
    <div class="form-floating mb-3">
        <input type="text" class="form-control" name="Name" id="Name" placeholder="name">
        <label for="floatingInput">Name</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" name="Surname" id="Surname" placeholder="surname">
        <label for="floatingInput">Surname</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" name="Age" id="Age" placeholder="18">
        <label for="floatingInput">Age</label>
    </div>
    <button type="submit" class="btn btn-info">Submit</button>
</form>

@if (Model != null)
{
    @if (Convert.ToInt32(Model.Age) < 18)
    {
        <div class="alert alert-danger position-fixed top-0 start-0 w-100" role="alert">
            Kayit Olamazsiniz
        </div>
    }
    else
    {
        <div class="alert alert-success position-fixed top-0 start-0 w-100" role="alert">
            Hosgeldiniz
        </div>

    }
}
@* @{
    <li>Name:@Model.Name</li>
    <li>Surname:@Model.Surname</li>
    <li>Age:@Model.Age</li>
} *@

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index7.cshtml
<div>
    Index 7
</div>

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index8.cshtml
<div>
    index 8
</div>

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/MvcOnIkiSubat/Views/ModelUygulama/Index9.cshtml
<div>
    index 9
</div>