MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/YirmiYediSubat/Entities/Malzeme.cs
namespace YirmiYediSubat.Entities
{
    public class Malzeme
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public int Fiyat { get; set; }
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/YirmiYediSubat/Models/ErrorViewModel.cs
namespace YirmiYediSubat.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/YirmiYediSubat/Models/Ogrenci.cs
namespace YirmiYediSubat.Models
{
    public class Ogrenci
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Numara { get; set; }

    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/YirmiYediSubat/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using YirmiYediSubat.Models;

namespace YirmiYediSubat.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Index2(int id)
        {
            List<Ogrenci> ogrenciler = new List<Ogrenci>()
                {
                new Ogrenci { Id = 1, Ad="Ali",Soyad="Kara",Numara="as1123"},
                new Ogrenci { Id = 2, Ad="Ali2",Soyad="Kara2",Numara="as2123"},
                new Ogrenci { Id = 3, Ad="Ali3",Soyad="Kara3",Numara="as3123"},
                new Ogrenci { Id = 4, Ad="Ali4",Soyad="Kara4",Numara="as4123"},
            };
            var ogrenci = ogrenciler.FirstOrDefault(o => o.Id == id);
            return new JsonResult(ogrenci);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/YirmiYediSubat/Controllers/MalzemeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using YirmiYediSubat.Context;
using YirmiYediSubat.Entities;

namespace YirmiYediSubat.Controllers
{
    public class MalzemeController : Controller
    {
        private YirmiYediSubatDbContext _db;
        public MalzemeController(YirmiYediSubatDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetTableList()
        {
            return PartialView(_db.Malzemeler.ToList());
        }
        public IActionResult Listeleme()
        {
            return new JsonResult(_db.Malzemeler.ToList());
        }
        public IActionResult Add(Malzeme malzeme)
        {
            _db.Malzemeler.Add(malzeme);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var deleteMalzeme = _db.Malzemeler.Find(id);
            _db.Malzemeler.Remove(deleteMalzeme);
            _db.SaveChanges(true);
            return Ok();
        }
    }
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/YirmiYediSubat/Views/Malzeme/GetTableList.cshtml
@using YirmiYediSubat.Entities
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<Malzeme>
<style>
    tr {
        text-align: center;
    }
</style>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Ad</th>
            <th>Fiyat</th>
            <th>Islemler</th>

        </tr>
    </thead>
    <tbody>
        @if (Model.Count == 0)
        {
            <tr>
                <td colspan="4">Maleme Bulunamadi</td>
            </tr>
        }

        else
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Ad</td>
                    <td>@item.Fiyat</td>
                    <td>
                        <button onclick="Delete(@item.Id)" class="btn btn-outline-danger">Sil</button>
                        <button onclick="Update(@item.Id)" class="btn btn-outline-warning">Duzenle</button>
                    </td>
                </tr>
            }
            <form id="form-tr">
            <tr>
                <td></td>
                <td><input name="Ad" id="Ad" /></td>
                <td><input name="Fiyat" id="Fiyat" /></td>
                <td><button class="btn btn-success w-100" id="btn-ekle-2" type="button">Ekle</button></td>
            </tr>
            </form>
        }

    </tbody>

</table>

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/YirmiYediSubat/Views/Malzeme/Index.cshtml
@using YirmiYediSubat.Entities
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="w-100 d-flex justify-content-between align-items-center">
    <button class="btn btn-warning" id="table-btn">Tablo Getir</button>
    <button class="btn btn-warning" id="table-btn-2">Tablo Getir 2</button>

</div>
<div class="table-container text-center">
</div>
@model Malzeme

<form id="form-malzeme">
    <div class="form-group">
        <label class="form-label">Ad</label>
        <input name="Ad" type="text" class="form-control" />
    </div>
    <div class="form-group mb-2">
        <label class="form-label">Fiyat</label>
        <input name="Fiyat" type="number" class="form-control" />
    </div>
    <button type="button" id="btn-malzeme-add" class="btn btn-success">Ekle</button>
</form>

@section Scripts {
    <script src="./js/ajaxCustom.js"></script>
}

MuratCihanUludag/MuratCihanMVC/MuratCihanMvc/YirmiYediSubat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YirmiYediSubat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YirmiYediSubat.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">YirmiYediSubat</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Malzeme" asp-action="Index">Malzeme</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - YirmiYediSubat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>